import Head from "next/head";
import Link from "next/link";
import { handler } from "../api";
import Layout from "../../components/Layout";

const API_KEY = "9hUvOqGGdnCBvGKg4EB3L7mGdBC8hKKJ";

export default function Section({ results, title }) {
  return (
    <Layout>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1> About {results.length} results </h1>
        <ul>
          {results?.map((post) => (
            <Link href={`section/${post.section}`}>
              <li>{post.display_name}</li>
            </Link>
          ))}
        </ul>
      </main>
    </Layout>
  );
}

export async function getStaticProps() {
  const results = await handler(
    `https://api.nytimes.com/svc/news/v3/content/section-list.json?api-key=${API_KEY}`
  );
  return {
    props: {
      results,
      title: "Section",
    },
  };
}
